// CFA Level I Question Bank — prototype data
// Structure: TOPICS -> modules -> questions
// To expand: push more question objects into any module's `questions` array.
// Each question: { q, options: [4 strings], correct: index (0-3), explain: string }

const TOPICS = [
  {
    id: "qm", name: "Quantitative Methods",
    modules: [
      { id: "qm-rates", name: "Rates and Returns", questions: [
        { q: "An interest rate can be interpreted as all of the following EXCEPT:", options: ["A required rate of return", "A discount rate", "A measure of default probability", "An opportunity cost"], correct: 2, explain: "Interest rates are interpreted as required returns, discount rates, or opportunity costs — the sum of a real risk-free rate plus premiums for risk. They are not themselves a probability of default; default risk is one of the premiums that helps determine the rate." },
        { q: "A portfolio has cash inflows early in the period that coincide with strong performance, followed by large withdrawals. Compared to the time-weighted return, the money-weighted return will most likely be:", options: ["Lower, because withdrawals are unaffected by returns", "Higher, because more money was invested during the period of strong performance", "Identical, since both measures ignore cash flow timing", "Impossible to determine without the exact discount rate"], correct: 1, explain: "The money-weighted return (an IRR) is sensitive to the timing and size of cash flows. Because more capital was invested when performance was strong, that period is weighted more heavily, pushing the money-weighted return above the time-weighted return, which treats each sub-period equally regardless of cash flow size." },
        { q: "An investment returns 5% in year 1 and 15% in year 2. What is the geometric mean annual return?", options: ["10.00%", "9.89%", "10.50%", "9.54%"], correct: 1, explain: "Geometric mean = [(1.05)(1.15)]^(1/2) − 1 = (1.2075)^0.5 − 1 ≈ 1.0989 − 1 = 9.89%. The geometric mean is always less than or equal to the arithmetic mean (10.00%) when returns vary." },
        { q: "Which return measure is most appropriate for evaluating a portfolio manager's investment skill when the manager does not control the timing or size of client deposits and withdrawals?", options: ["Money-weighted rate of return", "Time-weighted rate of return", "Nominal rate of return", "Bank discount yield"], correct: 1, explain: "Because the manager has no control over external cash flows, the time-weighted return isolates the return earned on the portfolio itself, making it the appropriate measure of manager skill. The money-weighted return conflates client cash-flow timing with performance." }
      ]},
      { id: "qm-tvm", name: "Time Value of Money in Finance", questions: [
        { q: "The cash flow additivity principle is most directly used to:", options: ["Calculate the standard deviation of a return series", "Derive implied forward interest rates from spot rates under no-arbitrage", "Determine the skewness of an asset's return distribution", "Compute the sample correlation between two assets"], correct: 1, explain: "The cash flow additivity principle states that cash flows occurring at the same point in time can be combined, which underlies no-arbitrage pricing and is used to derive implied forward rates, forward exchange rates, and option values." },
        { q: "A fixed-income instrument's implied return, given its current price and future cash flows, is best described as:", options: ["The coupon rate stated on the instrument", "The discount rate that equates the present value of future cash flows to the current price", "The average of all historical yields on the instrument", "The rate set by the central bank"], correct: 1, explain: "The implied return is the internal rate of return — the discount rate that makes the present value of the promised future cash flows equal to the instrument's current price." },
        { q: "For an equity instrument, the implied growth rate given a required return and current price is calculated using which type of model?", options: ["A dividend discount model solved for growth", "The capital asset pricing model solved for beta", "A binomial option pricing model", "A regression model solved for the slope coefficient"], correct: 0, explain: "Given the present value (price), the required return, and expected cash flows, a dividend discount model (e.g., the Gordon growth model) can be solved algebraically for the implied growth rate embedded in the current price." },
        { q: "Which statement about present value (PV) calculations for fixed-income versus equity instruments is most accurate?", options: ["Fixed-income PV uses only nominal cash flows while equity PV uses only real cash flows", "Both rely on discounting expected future cash flows back to today at an appropriate rate", "Equity valuation never uses the time value of money", "Fixed-income cash flows are never known with certainty, unlike equity cash flows"], correct: 1, explain: "Both fixed-income and equity present value calculations discount expected future cash flows (coupons/principal or dividends/terminal value) back to the present using an appropriate discount rate that reflects risk and the time value of money." }
      ]},
      { id: "qm-stats", name: "Statistical Measures of Asset Returns", questions: [
        { q: "A return distribution with positive excess kurtosis relative to the normal distribution is described as:", options: ["Platykurtic", "Leptokurtic", "Mesokurtic", "Skewed"], correct: 1, explain: "Leptokurtic distributions have fatter tails and a higher peak than the normal distribution (positive excess kurtosis), meaning extreme outcomes are more likely than under a normal distribution." },
        { q: "If a return distribution is negatively skewed, which relationship among mean, median, and mode is most likely?", options: ["Mean > Median > Mode", "Mode > Median > Mean", "Mean = Median = Mode", "Median > Mode > Mean"], correct: 1, explain: "In a negatively skewed distribution, the long left tail pulls the mean down. The typical ordering is Mode > Median > Mean, the reverse of a positively skewed distribution." },
        { q: "A correlation coefficient of −0.85 between two assets' returns indicates:", options: ["The assets move in the same direction almost all the time with high consistency", "A strong tendency for the assets to move in opposite directions", "No meaningful linear relationship between the two assets", "That one asset causes the other's price to fall"], correct: 1, explain: "A correlation of −0.85 is close to −1, indicating a strong negative linear relationship (the returns tend to move in opposite directions). Correlation measures association, not causation." },
        { q: "Which measure of dispersion gives disproportionately more weight to large deviations from the mean?", options: ["Mean absolute deviation", "Range", "Variance", "Interquartile range"], correct: 2, explain: "Variance squares each deviation from the mean before averaging, so larger deviations are weighted disproportionately more heavily than smaller ones, unlike mean absolute deviation which weights deviations linearly." }
      ]}
    ]
  },
  {
    id: "econ", name: "Economics",
    modules: [
      { id: "econ-cycles", name: "Understanding Business Cycles", questions: [
        { q: "During the contraction phase of the business cycle, which of the following is most typically observed?", options: ["Rising inventory-to-sales ratios and falling resource utilization", "Accelerating credit expansion and peak capacity utilization", "Rapidly rising housing starts", "A sharp increase in business capital expenditures"], correct: 0, explain: "In a contraction, demand falls faster than production adjusts, so inventory-to-sales ratios rise and resource (capacity) utilization declines. Credit expansion, capacity peaks, and rising capex are more typical of the late expansion phase." },
        { q: "A credit cycle is best described as:", options: ["The pattern of interest rate changes set solely by the central bank", "Fluctuations in the availability and cost of credit that can amplify the business cycle", "The seasonal pattern of consumer credit card spending", "A synonym for the business cycle itself"], correct: 1, explain: "The credit cycle refers to alternating phases of credit expansion and contraction (availability and pricing of credit), which interact with and can amplify swings in the broader business cycle, though it is a related but distinct concept." },
        { q: "Which economic indicator is generally classified as a leading indicator of the business cycle?", options: ["Unemployment rate", "Building permits", "GDP", "Corporate profits (reported quarterly, after the fact)"], correct: 1, explain: "Building permits tend to turn before the broader economy, since developers respond to expectations of future demand, making them a leading indicator. Unemployment is typically a lagging indicator." },
        { q: "External trade sector activity over the business cycle is best characterized by:", options: ["Imports and exports that remain constant regardless of the cycle phase", "Imports typically rising with domestic expansion, while exports depend more on trading partners' cycles", "Exports always leading domestic GDP by exactly two quarters", "Trade balances that are unaffected by exchange rates"], correct: 1, explain: "Imports tend to rise with domestic income and expansion (reflecting domestic demand), while exports are more heavily influenced by economic conditions and demand in trading-partner countries." }
      ]},
      { id: "econ-mon", name: "Monetary Policy", questions: [
        { q: "Which of the following is the primary objective typically pursued by modern central banks through monetary policy?", options: ["Maximizing short-term equity market returns", "Price stability, often alongside supporting sustainable economic growth", "Directly setting wage levels across all industries", "Balancing the government's fiscal budget"], correct: 1, explain: "Most central banks are mandated to pursue price stability (controlling inflation), and many also have a secondary objective of supporting growth and employment. Fiscal budgeting is a government/fiscal policy function, not monetary policy." },
        { q: "An increase in the policy rate by a central bank is generally intended to transmit through the economy by:", options: ["Lowering borrowing costs and stimulating investment", "Raising borrowing costs, which dampens consumption and investment, slowing inflation", "Directly increasing government spending", "Immediately fixing the exchange rate"], correct: 1, explain: "Raising the policy rate increases the cost of borrowing, which is expected to reduce consumption and investment spending, cooling demand and inflationary pressure through the monetary transmission mechanism." },
        { q: "A central bank using exchange rate targeting as its primary tool would most likely:", options: ["Ignore the level of its own currency entirely", "Adjust domestic interest rates and intervene in FX markets to maintain a target exchange rate", "Set targets only for domestic unemployment", "Use exchange rate targeting only in economies with fully floating currencies and no intervention"], correct: 1, explain: "Under exchange rate targeting, a central bank manages domestic interest rates and may intervene directly in currency markets to keep its exchange rate at or near a specific target level or within a target band, often used by smaller open economies." },
        { q: "A key limitation of monetary policy is that it:", options: ["Can perfectly control real economic output in the short run", "Operates with lags and may be less effective when interest rates are already very low", "Has no effect on inflation expectations", "Is implemented instantly with no time delay"], correct: 1, explain: "Monetary policy works with transmission lags, and its effectiveness can be constrained near the zero (or effective) lower bound on interest rates, limiting the central bank's ability to further stimulate the economy through conventional rate cuts." }
      ]}
    ]
  },
  {
    id: "ci", name: "Corporate Issuers",
    modules: [
      { id: "ci-capstruct", name: "Capital Structure", questions: [
        { q: "Under Modigliani–Miller Proposition I (no taxes), a firm's capital structure:", options: ["Directly determines the firm's total value", "Has no effect on the firm's total value", "Only matters if the firm has no debt", "Determines the firm's total value only during recessions"], correct: 1, explain: "MM Proposition I (without taxes) states that, under restrictive assumptions (no taxes, no bankruptcy costs, efficient markets), the value of the firm is independent of its capital structure — how it is financed does not change total firm value." },
        { q: "All else equal, an increase in a company's cost of debt while its target capital structure weights remain unchanged will:", options: ["Decrease the weighted-average cost of capital (WACC)", "Increase the WACC", "Have no effect on WACC", "Always increase the equity risk premium"], correct: 1, explain: "WACC is a weighted average of the costs of debt and equity. If the cost of debt rises and the weights are held constant, the weighted average cost of capital increases, all else equal." },
        { q: "A company's optimal capital structure is generally understood as the mix of debt and equity that:", options: ["Uses the maximum possible amount of debt", "Minimizes the firm's WACC and maximizes firm value", "Avoids debt entirely to minimize risk", "Is fixed permanently and never adjusted"], correct: 1, explain: "The optimal (or target) capital structure balances the tax benefits and lower cost of debt against increasing financial distress/bankruptcy costs, minimizing WACC and thereby maximizing the value of the firm." },
        { q: "Which factor would most likely lead a company to use a higher proportion of debt in its capital structure?", options: ["Highly volatile and unpredictable operating cash flows", "Stable, predictable cash flows and tangible assets that can serve as collateral", "A high level of financial distress risk in its industry", "A preference by managers to avoid financial leverage"], correct: 1, explain: "Companies with stable cash flows and tangible collateralizable assets can more safely service debt obligations, making them better candidates for higher leverage than firms with volatile cash flows or few tangible assets." }
      ]},
      { id: "ci-capinv", name: "Capital Investments and Capital Allocation", questions: [
        { q: "A project has a positive net present value (NPV). This indicates that the project is expected to:", options: ["Return exactly the cost of capital", "Increase the value of the firm, since discounted benefits exceed discounted costs", "Reduce the value of the firm", "Have no effect on firm value"], correct: 1, explain: "A positive NPV means the present value of a project's expected cash inflows exceeds the present value of its costs (using the appropriate discount rate), so accepting the project is expected to increase firm value." },
        { q: "The internal rate of return (IRR) of a project is defined as the discount rate at which:", options: ["NPV equals zero", "NPV is maximized", "The payback period equals the project's life", "ROIC equals WACC exactly at all times"], correct: 0, explain: "IRR is the discount rate that sets the net present value of a project's cash flows equal to zero — it is the project's break-even required return." },
        { q: "Return on invested capital (ROIC) is best used in capital allocation to:", options: ["Replace the need for any NPV or IRR analysis", "Assess how efficiently a company generates profit from the capital already invested in its operations", "Determine a company's dividend payout ratio", "Calculate a bond's yield to maturity"], correct: 1, explain: "ROIC measures after-tax operating profit relative to invested capital, providing a way to evaluate how efficiently existing capital investments are generating returns — often compared to WACC to judge whether value is being created." },
        { q: "A common pitfall in the capital allocation process is:", options: ["Using too many independent scenario analyses", "Basing decisions on sunk costs rather than incremental cash flows", "Considering the time value of money", "Estimating a project's discount rate too carefully"], correct: 1, explain: "A classic capital allocation pitfall is including sunk costs (costs already incurred and not recoverable) in the decision analysis, when only incremental (relevant) future cash flows should be used to evaluate a project." }
      ]}
    ]
  },
  {
    id: "fsa", name: "Financial Statement Analysis",
    modules: [
      { id: "fsa-income", name: "Analyzing Income Statements", questions: [
        { q: "Under the general principle of revenue recognition, revenue should be recognized when:", options: ["Cash is received, regardless of when goods are delivered", "Control of goods or services has transferred to the customer", "The contract is signed, regardless of delivery", "The company's fiscal year ends"], correct: 1, explain: "Modern revenue recognition standards (e.g., IFRS 15 / ASC 606) require recognizing revenue when control of the promised goods or services transfers to the customer, not simply upon cash receipt or contract signing." },
        { q: "A cost that provides economic benefit over multiple future periods should generally be:", options: ["Expensed immediately in full", "Capitalized and depreciated or amortized over its useful life", "Ignored on the financial statements", "Recorded directly to retained earnings"], correct: 1, explain: "Costs expected to generate benefits over multiple future periods (e.g., purchase of equipment) are capitalized as assets and their cost is systematically allocated to expense (depreciated/amortized) over the periods benefited, matching expenses with revenues." },
        { q: "A non-recurring gain from the sale of a discontinued operation should be analyzed by an analyst by:", options: ["Including it in projections of future recurring earnings", "Excluding it when assessing the sustainable, ongoing earnings power of the business", "Ignoring the entire income statement", "Adding it to revenue from continuing operations"], correct: 1, explain: "Non-recurring items like gains on discontinued operations are not expected to repeat, so analysts typically exclude them when evaluating a company's sustainable, ongoing (core) earnings power for forecasting purposes." },
        { q: "Diluted EPS differs from basic EPS in that diluted EPS:", options: ["Ignores preferred dividends entirely", "Reflects the potential dilution from convertible securities, options, and warrants", "Is always higher than basic EPS", "Excludes discontinued operations"], correct: 1, explain: "Diluted EPS incorporates the effect of potentially dilutive securities (convertible bonds/preferred, stock options, warrants) as if they were converted/exercised, so diluted EPS is typically lower than or equal to basic EPS, never higher." }
      ]},
      { id: "fsa-ratios", name: "Financial Analysis Techniques", questions: [
        { q: "The DuPont decomposition of return on equity (ROE) breaks it down into which three components?", options: ["Current ratio, quick ratio, and cash ratio", "Net profit margin, asset turnover, and financial leverage", "Gross margin, operating margin, and net margin", "P/E ratio, P/B ratio, and dividend yield"], correct: 1, explain: "The standard three-factor DuPont decomposition expresses ROE as Net Profit Margin × Asset Turnover × Financial Leverage (equity multiplier), showing how profitability, efficiency, and leverage each contribute to ROE." },
        { q: "A company's current ratio increases from 1.2 to 2.5 primarily because it issued long-term debt and held the proceeds in cash. This is best interpreted as:", options: ["A clear sign of deteriorating liquidity", "Improved short-term liquidity, at least on this measure, though it doesn't necessarily reflect improved operating performance", "Irrelevant to the analysis of liquidity", "A violation of accounting standards"], correct: 1, explain: "The current ratio (current assets / current liabilities) rises because cash (a current asset) increased while current liabilities didn't, mechanically improving the ratio. But this reflects a financing decision, not improved operating efficiency or profitability." },
        { q: "Which ratio is most useful for assessing a company's solvency (long-term ability to meet obligations)?", options: ["Inventory turnover", "Debt-to-equity ratio", "Receivables turnover", "Current ratio"], correct: 1, explain: "Solvency ratios like debt-to-equity assess a company's ability to meet its long-term/total obligations, reflecting its capital structure and leverage. Turnover ratios measure operating efficiency, and the current ratio measures short-term liquidity." },
        { q: "Common-size financial statements are most useful for:", options: ["Comparing companies of different sizes by expressing line items as a percentage of a common base", "Eliminating the need for ratio analysis entirely", "Converting all figures into a foreign currency", "Adjusting for inflation only"], correct: 0, explain: "Common-size statements express each income statement item as a percentage of revenue, and each balance sheet item as a percentage of total assets, enabling meaningful comparison across companies of different sizes or across time." }
      ]}
    ]
  },
  {
    id: "eq", name: "Equity Investments",
    modules: [
      { id: "eq-mkteff", name: "Market Efficiency", questions: [
        { q: "Under the semi-strong form of market efficiency, security prices reflect:", options: ["Only past price and volume data", "All publicly available information, including financial statements", "All information, including private/insider information", "No information at all"], correct: 1, explain: "Semi-strong-form efficiency holds that prices reflect all publicly available information (including financial statement data), meaning fundamental analysis based on public data should not consistently generate abnormal returns. Only insider information could theoretically provide an edge." },
        { q: "If markets are strong-form efficient, which activity would be expected to consistently generate abnormal risk-adjusted returns?", options: ["Fundamental analysis of public filings", "Technical analysis of price patterns", "None — not even trading on private information", "Trading on material non-public (insider) information"], correct: 2, explain: "Under strong-form efficiency, prices already reflect all information, public and private, so no strategy — not even trading on insider information — could reliably generate abnormal risk-adjusted returns." },
        { q: "A market anomaly, such as the small-firm effect, is best described as:", options: ["Proof that markets are always perfectly efficient", "A pattern in returns that appears to contradict market efficiency", "A regulatory rule about firm size", "A type of derivative contract"], correct: 1, explain: "Market anomalies are empirical patterns (e.g., small-firm effect, January effect) that appear to be inconsistent with the efficient market hypothesis, suggesting opportunities to earn abnormal returns, though explanations vary (risk premia, behavioral biases, or data mining)." },
        { q: "Behavioral finance is most relevant to understanding market efficiency because it:", options: ["Assumes all investors are perfectly rational at all times", "Offers explanations for anomalies based on systematic psychological biases in investor decision-making", "Proves that technical analysis always outperforms fundamental analysis", "Is unrelated to the study of asset pricing"], correct: 1, explain: "Behavioral finance studies how psychological biases (overconfidence, loss aversion, herding, etc.) can lead to systematic mispricings or anomalies that traditional efficient-market theory, which assumes rational investors, struggles to explain." }
      ]},
      { id: "eq-val", name: "Equity Valuation: Concepts and Basic Tools", questions: [
        { q: "If a stock's intrinsic value (from a valuation model) exceeds its current market price, the stock is most likely:", options: ["Overvalued", "Fairly valued", "Undervalued", "Impossible to assess"], correct: 2, explain: "When estimated intrinsic value exceeds the market price, the security is considered undervalued by the model/analyst — implying the market price may rise toward the estimated intrinsic value if the market later agrees with the analyst's assessment." },
        { q: "The Gordon (constant) growth dividend discount model is most appropriate for valuing a company that:", options: ["Pays no dividends and is not expected to for the foreseeable future", "Has a stable, mature dividend growth rate expected to continue indefinitely", "Is in a high-growth start-up phase with highly volatile earnings", "Recently emerged from bankruptcy with negative equity"], correct: 1, explain: "The Gordon growth model assumes dividends grow at a single constant rate forever, so it is best suited to stable, mature companies with a long history of steady dividend growth — not high-growth or non-dividend-paying firms." },
        { q: "The price-to-earnings (P/E) multiple is most directly related to which fundamental driver?", options: ["The company's expected future growth, payout ratio, and required return", "Only the company's total revenue", "The company's inventory turnover ratio", "The number of shares authorized but not issued"], correct: 0, explain: "The justified P/E multiple, derived from the dividend discount model, is a function of the expected dividend payout ratio, expected growth rate, and the required rate of return — higher growth and payout (relative to required return) support a higher justified P/E." },
        { q: "An enterprise value (EV) multiple, such as EV/EBITDA, is often preferred over equity multiples like P/E when comparing companies with:", options: ["Identical capital structures across the board", "Different capital structures (levels of debt), since EV captures the whole firm's capital providers", "No debt whatsoever", "Identical share counts"], correct: 1, explain: "EV multiples use enterprise value (which includes both debt and equity claims) in the numerator and a pre-interest metric like EBITDA in the denominator, making them less distorted by differences in capital structure/leverage across comparable companies than equity-only multiples like P/E." }
      ]}
    ]
  },
  {
    id: "fi", name: "Fixed Income",
    modules: [
      { id: "fi-valuation", name: "Fixed-Income Bond Valuation: Prices and Yields", questions: [
        { q: "A bond is priced at a discount to par. Which relationship between coupon rate and yield-to-maturity (YTM) must hold?", options: ["Coupon rate > YTM", "Coupon rate < YTM", "Coupon rate = YTM", "There is no consistent relationship"], correct: 1, explain: "A bond trades at a discount (price below par) when its yield-to-maturity exceeds its coupon rate — investors require a higher return than the coupon provides, so they pay less than par to compensate." },
        { q: "All else equal, as a bond's yield-to-maturity increases, its price will:", options: ["Increase", "Decrease", "Remain unchanged", "Move unpredictably"], correct: 1, explain: "Bond price and yield are inversely related: as required yields rise, the present value of the bond's fixed future cash flows falls, so the bond's price decreases, all else equal." },
        { q: "Matrix pricing is a technique used to:", options: ["Estimate the price of an infrequently traded bond using yields of comparable, more liquid bonds", "Calculate exact yields using a matrix algebra system for all bonds", "Set central bank policy rates", "Determine equity index weights"], correct: 0, explain: "Matrix pricing estimates the required yield (and thus price) for a bond that doesn't trade frequently or lacks a reliable market price, by referencing the yields of comparable bonds with similar credit quality, coupon, and maturity that do trade actively." },
        { q: "Between two otherwise identical bonds, the one with the longer maturity will generally exhibit:", options: ["Lower price sensitivity to a change in yield", "Higher price sensitivity to a change in yield", "Identical price sensitivity regardless of maturity", "No relationship between maturity and price sensitivity"], correct: 1, explain: "All else equal, longer-maturity bonds have greater price sensitivity (higher duration) to changes in yield, because their cash flows are received further in the future and are discounted over a longer horizon." }
      ]},
      { id: "fi-irr", name: "Interest Rate Risk and Return", questions: [
        { q: "Macaulay duration is best described as:", options: ["The bond's coupon rate expressed in years", "The weighted-average time to receive the bond's cash flows, weighted by present value", "The bond's current market price divided by par value", "The number of years until the bond's credit rating is reviewed"], correct: 1, explain: "Macaulay duration is a weighted average of the times to each cash flow, where the weights are the present value of each cash flow as a proportion of the bond's total present value (price) — it can be interpreted as the bond's effective average maturity." },
        { q: "An investor's investment horizon exactly equals the bond's Macaulay duration. This is significant because at that point:", options: ["The investor is fully exposed to reinvestment risk only", "Price risk and reinvestment risk approximately offset, immunizing the portfolio against small parallel yield changes", "The bond will have zero price risk forever", "The bond's coupon rate becomes irrelevant"], correct: 1, explain: "When the investment horizon equals Macaulay duration, a rise in yields (bad for price, good for reinvestment income) approximately offsets a fall in yields (good for price, bad for reinvestment income), immunizing the realized return against small, one-time parallel shifts in rates." },
        { q: "The total return from investing in a fixed-rate bond comes from which sources?", options: ["Coupon and principal payments, reinvestment income on those payments, and any capital gain or loss at sale/maturity", "Only the coupon payments", "Only price appreciation", "Currency translation gains exclusively"], correct: 0, explain: "A bond's total return combines coupon and principal cash flows, income earned from reinvesting those cash flows, and any capital gain or loss if the bond is sold before maturity or matures at a different price than purchase." },
        { q: "If an investor's horizon is shorter than the bond's Macaulay duration, the investor is most exposed to:", options: ["Primarily reinvestment risk", "Primarily price (market) risk, since the bond likely must be sold before maturity", "No interest rate risk at all", "Only credit risk"], correct: 1, explain: "When the horizon is shorter than duration, price risk dominates: the investor is more likely to need to sell the bond before it matures, so an increase in yields (which lowers bond prices) poses a greater relative threat than the benefit of higher reinvestment income." }
      ]}
    ]
  },
  {
    id: "der", name: "Derivatives",
    modules: [
      { id: "der-instruments", name: "Forward Commitment and Contingent Claim Features and Instruments", questions: [
        { q: "A forward commitment differs from a contingent claim in that a forward commitment:", options: ["Gives the holder the right, but not the obligation, to transact", "Obligates both parties to transact on agreed-upon terms at a future date", "Has no counterparty risk whatsoever", "Can only be written on interest rates"], correct: 1, explain: "Forward commitments (forwards, futures, swaps) obligate both parties to complete the transaction on the agreed terms. Contingent claims (options) give one party the right, but not the obligation, to transact, contingent on some future event or price level." },
        { q: "The profit to the holder of a long call option position at expiration, if the option expires in-the-money, equals:", options: ["The strike price minus the underlying price, minus the premium paid", "The underlying price minus the strike price, minus the premium paid", "Always zero regardless of the underlying price", "The premium received"], correct: 1, explain: "A long call's payoff at expiration is max(0, S − X). Profit subtracts the premium originally paid: profit = max(0, S − X) − premium. When in-the-money, this simplifies to (S − X) − premium." },
        { q: "A swap contract can be thought of as most similar to:", options: ["A single forward contract", "A series (portfolio) of forward contracts with different settlement dates", "An equity share", "A zero-coupon bond only"], correct: 1, explain: "A plain-vanilla swap (e.g., interest rate swap) can be decomposed into a series of forward contracts, each corresponding to one exchange of cash flows on a future settlement date, though swaps are typically priced/valued somewhat differently in practice." },
        { q: "Which of the following is a key benefit that derivative instruments provide to investors and issuers?", options: ["They eliminate all forms of financial risk", "They allow for efficient risk transfer and price discovery", "They guarantee positive returns", "They are free of counterparty risk in all cases"], correct: 1, explain: "Derivatives allow market participants to transfer specific risks (e.g., hedgers transferring price risk to speculators) efficiently and contribute to price discovery, but they do not eliminate risk entirely and can carry counterparty risk, especially in OTC markets." }
      ]},
      { id: "der-options", name: "Pricing and Valuation of Options", questions: [
        { q: "An option's time value at any point before expiration equals:", options: ["The option's market price minus its exercise (intrinsic) value", "The strike price minus the current stock price", "Always zero for European options", "The risk-free rate multiplied by time to expiration"], correct: 0, explain: "An option's premium consists of intrinsic value (exercise value) plus time value. Time value = option price − intrinsic value, and it reflects the possibility that the option could become more valuable before expiration." },
        { q: "All else equal, an increase in the volatility of the underlying asset will:", options: ["Decrease the value of both call and put options", "Increase the value of both call and put options", "Increase call value but decrease put value", "Have no effect on either option's value"], correct: 1, explain: "Higher volatility increases the value of both calls and puts because it raises the probability of larger favorable price swings, while the option holder's downside is limited to the premium paid — asymmetric payoff structure benefits from more volatility." },
        { q: "Put–call parity for European options establishes a relationship among:", options: ["Call price, put price, underlying price, and present value of the strike price", "Only the call and put prices, with no reference to the underlying", "Historical volatility and implied volatility exclusively", "Only American-style options"], correct: 0, explain: "Put–call parity states: Call price + PV(Strike) = Put price + Underlying price (for European options on the same underlying, strike, and expiration), allowing any one of the four variables to be derived from the other three, and enabling synthetic replication." },
        { q: "In a one-period binomial option pricing model, the option is valued using:", options: ["Real-world (actual) probabilities of the up and down states", "Risk-neutral probabilities that make the underlying's expected return equal the risk-free rate", "Historical average stock returns over the past decade", "The company's dividend payout ratio only"], correct: 1, explain: "The binomial model values options using risk-neutral probabilities — probabilities constructed so that the expected return on the underlying equals the risk-free rate — allowing the option's expected payoff to be discounted at the risk-free rate, independent of investors' actual risk preferences." }
      ]}
    ]
  },
  {
    id: "ai", name: "Alternative Investments",
    modules: [
      { id: "ai-hedge", name: "Hedge Funds", questions: [
        { q: "Compared to traditional long-only mutual funds, hedge funds are most distinguished by their:", options: ["Complete prohibition on using leverage or derivatives", "Greater flexibility to use leverage, short selling, and derivatives, along with less regulatory constraint", "Requirement to fully disclose all holdings daily to the public", "Guarantee of positive absolute returns in all market conditions"], correct: 1, explain: "Hedge funds typically have more flexible investment mandates than traditional mutual funds, including the ability to use leverage, take short positions, and use derivatives extensively, along with fewer regulatory constraints — though this comes with less transparency and higher risk, not a guarantee of positive returns." },
        { q: "A 'fund of hedge funds' investment vehicle primarily offers investors:", options: ["Direct ownership of a single hedge fund's positions", "Diversification across multiple underlying hedge funds through one investment, along with an additional layer of fees", "Guaranteed liquidity superior to any single hedge fund", "Elimination of manager-specific risk entirely"], correct: 1, explain: "A fund of hedge funds pools capital to invest across several underlying hedge funds, providing diversification across strategies/managers, but investors typically pay an additional layer of fees on top of the underlying funds' fees." },
        { q: "Hedge fund performance appraisal is complicated by which common issue?", options: ["Survivorship and backfill bias in hedge fund databases, which can overstate historical returns", "An absence of any risk in hedge fund strategies", "Complete standardization of fee structures across all hedge funds", "Daily, fully transparent public reporting requirements"], correct: 0, explain: "Hedge fund databases often suffer from survivorship bias (failed funds stop reporting and drop out) and backfill bias (new funds add historical returns only after choosing to report, often after a strong start), both of which tend to overstate average historical hedge fund performance." },
        { q: "A typical hedge fund fee structure combining a management fee and a performance fee is most often described as:", options: ["'0 and 0'", "'2 and 20'", "A flat annual fee only, with no performance component", "A fee based solely on assets under management with no incentive component"], correct: 1, explain: "A common (though not universal) traditional hedge fund fee structure is '2 and 20' — a 2% annual management fee on assets under management plus a 20% performance (incentive) fee on profits, often subject to a hurdle rate and/or high-water mark." }
      ]},
      { id: "ai-re", name: "Real Estate and Infrastructure", questions: [
        { q: "Compared to publicly traded equities, direct real estate investments are generally characterized by:", options: ["Higher liquidity and lower transaction costs", "Lower liquidity, higher transaction costs, and the need for specialized valuation (appraisal-based)", "Continuous, exchange-based price discovery identical to stocks", "Complete absence of any income component"], correct: 1, explain: "Direct real estate is illiquid relative to public equities, involves significant transaction costs (legal, brokerage, due diligence), and is typically valued via periodic appraisals rather than continuous market pricing, which also affects reported volatility (smoothing)." },
        { q: "Infrastructure investments (e.g., toll roads, utilities) are often attractive to long-horizon investors primarily because they typically offer:", options: ["Highly volatile, unpredictable cash flows with no inflation linkage", "Stable, often inflation-linked cash flows over long time horizons", "Extremely short investment horizons of less than one year", "No correlation whatsoever with any economic variable"], correct: 1, explain: "Infrastructure assets often provide essential services with regulated or contracted revenue streams, resulting in relatively stable, sometimes inflation-linked cash flows over very long horizons — attractive to investors like pension funds with long-dated liabilities." },
        { q: "Which statement about the diversification benefits of real estate in a multi-asset portfolio is most accurate?", options: ["Real estate returns are always perfectly correlated with equities", "Real estate has historically shown relatively low correlation with traditional stocks and bonds, offering diversification benefits", "Real estate provides no income component, only capital appreciation", "Real estate cannot be included in institutional portfolios"], correct: 1, explain: "Real estate has historically exhibited relatively low correlation with traditional public equity and fixed-income markets, which can improve a portfolio's risk-adjusted return when added alongside stocks and bonds, in addition to providing income (rental yield) and potential appreciation." },
        { q: "Appraisal-based real estate valuations, compared to market-transaction-based valuations, tend to:", options: ["Overstate the true volatility of real estate returns", "Understate (smooth) the true volatility of real estate returns", "Perfectly match public market volatility", "Have no relationship to true asset volatility"], correct: 1, explain: "Because appraisals are performed periodically (not continuously) and appraisers often anchor to prior valuations, appraisal-based indices tend to smooth returns over time, understating the true (economic) volatility of the underlying real estate relative to what continuous market pricing would show." }
      ]}
    ]
  },
  {
    id: "pm", name: "Portfolio Management",
    modules: [
      { id: "pm-riskreturn1", name: "Portfolio Risk and Return: Part I", questions: [
        { q: "Combining two assets that are less than perfectly positively correlated in a portfolio will most likely:", options: ["Increase portfolio risk above the weighted average of the individual asset risks", "Reduce portfolio risk below the weighted average of the individual asset risks", "Have absolutely no effect on portfolio risk", "Only reduce risk if the assets have identical expected returns"], correct: 1, explain: "As long as correlation between two assets is less than +1, combining them in a portfolio produces diversification benefits: portfolio standard deviation is less than the simple weighted average of the individual assets' standard deviations." },
        { q: "The global minimum-variance portfolio is defined as the portfolio on the minimum-variance frontier that:", options: ["Has the highest possible expected return", "Has the lowest possible level of risk (standard deviation) among all feasible portfolios of risky assets", "Contains only risk-free assets", "Maximizes the Sharpe ratio"], correct: 1, explain: "The global minimum-variance portfolio is the single point on the minimum-variance frontier of risky assets that has the lowest standard deviation of any achievable combination of those assets, though it is not necessarily the portfolio with the best risk-adjusted (Sharpe) return." },
        { q: "An investor with a high degree of risk aversion, when choosing along the capital allocation line, will generally select a portfolio with:", options: ["A higher allocation to the risky asset portfolio and less to the risk-free asset", "A lower allocation to the risky asset portfolio and more to the risk-free asset", "100% allocation to the risky portfolio regardless of risk aversion", "An allocation determined solely by the risk-free rate"], correct: 1, explain: "More risk-averse investors, given a choice along the capital allocation line, will choose a combination with a smaller allocation to the risky asset portfolio and a larger allocation to the risk-free asset, accepting lower expected return for lower risk." },
        { q: "The efficient frontier of risky assets represents the set of portfolios that:", options: ["Minimize expected return for a given level of risk", "Maximize expected return for each given level of risk (or minimize risk for each given expected return)", "Contain only a single asset each", "Always include the risk-free asset"], correct: 1, explain: "The efficient frontier consists of portfolios of risky assets that offer the highest expected return for each level of risk (standard deviation), or equivalently, the lowest risk for each level of expected return — dominated portfolios below the frontier are excluded." }
      ]},
      { id: "pm-ips", name: "Basics of Portfolio Planning and Construction", questions: [
        { q: "The primary purpose of a written Investment Policy Statement (IPS) is to:", options: ["Guarantee a specific investment return", "Document the client's objectives, constraints, and the framework guiding investment decisions", "Replace the need for any asset allocation decision", "Serve only as a marketing document for the investment manager"], correct: 1, explain: "An IPS documents the investor's return and risk objectives along with constraints (liquidity, time horizon, taxes, legal/regulatory, unique circumstances), providing a disciplined framework that guides portfolio construction and helps evaluate performance — it does not guarantee any particular return." },
        { q: "The distinction between an investor's willingness and ability to take risk refers to:", options: ["The difference between an investor's psychological/attitudinal risk tolerance and their financial capacity to bear losses", "Two different names for exactly the same concept", "Willingness applies only to institutional investors, ability only to individuals", "A distinction that is irrelevant to constructing an IPS"], correct: 0, explain: "Willingness to take risk reflects an investor's psychological comfort with risk (attitude), while ability to take risk reflects their financial capacity to absorb losses (e.g., time horizon, wealth, income stability, liquidity needs) — the two can differ, and advisors generally default to the more conservative of the two when they conflict." },
        { q: "A pension fund with long-dated, predictable liabilities and strong sponsor backing would generally be considered to have:", options: ["A low ability to take risk", "A high ability to take risk", "No relevant time horizon", "An ability to take risk that is unrelated to its liabilities"], correct: 1, explain: "A long time horizon, predictable liabilities, and financial backing from a strong sponsor all increase an investor's financial capacity (ability) to bear investment risk, even if the fund's trustees might have varying attitudinal willingness to take risk." },
        { q: "Integrating ESG considerations into portfolio construction can most directly involve:", options: ["Ignoring financial return objectives entirely", "Screening, tilting, or otherwise adjusting the investable universe based on environmental, social, and governance factors alongside traditional analysis", "A practice that is prohibited under all investment policy statements", "Only applies to fixed-income portfolios, never equities"], correct: 1, explain: "ESG integration can take several forms — negative/positive screening, thematic investing, or ESG-factor tilting — incorporated alongside (not instead of) traditional risk/return analysis, and can apply across asset classes, not just equities or fixed income exclusively." }
      ]}
    ]
  },
  {
    id: "eth", name: "Ethical and Professional Standards",
    modules: [
      { id: "eth-code", name: "Code of Ethics and Standards of Professional Conduct", questions: [
        { q: "The CFA Institute Code of Ethics and Standards of Professional Conduct apply to:", options: ["Only CFA charterholders currently employed in portfolio management roles", "All CFA Institute members and candidates in the CFA Program, regardless of job function", "Only candidates who have passed all three exam levels", "Only individuals working in the United States"], correct: 1, explain: "The Code and Standards apply broadly to all CFA Institute members and candidates enrolled in the CFA Program, regardless of their specific job title, geographic location, or whether they have completed the full charter, as a condition of membership/candidacy." },
        { q: "How many Standards of Professional Conduct are there under the CFA Institute framework?", options: ["Five", "Six", "Seven", "Ten"], correct: 2, explain: "There are seven Standards of Professional Conduct (covering areas such as Professionalism, Integrity of Capital Markets, Duties to Clients, Duties to Employers, Investment Analysis, Conflicts of Interest, and Responsibilities as a CFA Member/Candidate), supporting the six components of the Code of Ethics." },
        { q: "A member who fails to maintain independence and objectivity by accepting gifts that could reasonably be expected to compromise their judgment would most likely violate:", options: ["Standard I(B): Independence and Objectivity", "Standard V(A): Diligence and Reasonable Basis", "Standard VII(A): Conduct as a CFA Candidate", "Standard III(D): Performance Presentation"], correct: 0, explain: "Standard I(B), Independence and Objectivity, addresses the need to maintain independence and objectivity in professional judgment, including guidance on accepting gifts, entertainment, or compensation that could be perceived as compromising that independence." },
        { q: "The CFA Institute Professional Conduct Program enforces the Code and Standards primarily through:", options: ["Criminal prosecution in national courts", "A disciplinary process that can result in sanctions such as suspension or revocation of membership/charter", "Fines paid directly to competing firms", "No formal enforcement mechanism exists"], correct: 1, explain: "The Professional Conduct Program investigates potential violations and can impose sanctions ranging from a private censure to suspension or revocation of CFA Institute membership and the right to use the CFA designation — it is a professional/organizational enforcement mechanism, not a criminal court process." }
      ]},
      { id: "eth-guidance", name: "Guidance for Standards I–VII", questions: [
        { q: "A CFA charterholder discovers a minor, unintentional error in a client's account statement two years ago. The most appropriate action under the Standards is to:", options: ["Ignore it since it happened long ago", "Correct the error and disclose it to the client promptly", "Wait for the client to notice it themselves", "Only disclose it if the client specifically asks about it"], correct: 1, explain: "Standards relating to duties to clients (fair dealing, suitability, loyalty/prudence) and diligence generally require prompt correction and disclosure of errors once discovered, regardless of how long ago they occurred, to maintain trust and act in the client's best interest." },
        { q: "Which practice would most likely help a firm comply with Standard III(B), Fair Dealing?", options: ["Giving preferred clients advance notice of upcoming recommendation changes before other clients", "Disseminating investment recommendations and changes to all clients on a systematic, simultaneous basis", "Allowing certain employees to trade ahead of client orders", "Providing different levels of research access based solely on relationship length with no disclosure"], correct: 1, explain: "Standard III(B), Fair Dealing, requires members to treat all clients fairly, which is best supported by disseminating material changes in recommendations to clients simultaneously (or as close to it as practicable) rather than favoring certain clients with early access." },
        { q: "Under Standard I(A), Knowledge of the Law, when local law is less strict than the CFA Institute Code and Standards, a member should:", options: ["Follow the less strict local law exclusively", "Adhere to the more strict of applicable law or the Code and Standards", "Ignore both and use personal judgment only", "Only follow the Code and Standards if operating in the United States"], correct: 1, explain: "Standard I(A) requires members to comply with applicable law, but when the Code and Standards impose a stricter standard than local law, members must adhere to the stricter requirement (the Code and Standards), rather than defaulting to a more permissive local rule." },
        { q: "A member preparing to leave an employer for a competing firm, under Standard IV(A), Loyalty, generally may NOT:", options: ["Update their personal résumé in their own time", "Solicit the employer's clients or take confidential firm records before formally departing", "Interview with the new firm outside of business hours", "Give reasonable advance notice of resignation"], correct: 1, explain: "Standard IV(A), Loyalty, generally prohibits members from soliciting the current employer's clients or misappropriating confidential information/records prior to actually leaving that employer, since such actions could harm the employer while the member is still employed there." }
      ]}
    ]
  }
];
